# Generated by Django 3.1.3 on 2022-04-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val1', models.CharField(default='', max_length=28)),
                ('val2', models.BooleanField(default=False)),
            ],
        ),
    ]
