# Generated by Django 3.1.3 on 2022-04-07 07:54

import django.core.validators
from django.db import migrations, models
import djongo.models.fields
import vendorBackend.models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorBackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('session', djongo.models.fields.EmbeddedField(model_container=vendorBackend.models.SessionModel)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=200)),
                ('_type', models.CharField(max_length=200)),
                ('document', djongo.models.fields.EmbeddedField(model_container=vendorBackend.models.DocumentModel)),
                ('certificate', djongo.models.fields.EmbeddedField(model_container=vendorBackend.models.CertificateModel)),
                ('license', djongo.models.fields.EmbeddedField(model_container=vendorBackend.models.LicenseModel)),
                ('rating', models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
