# Generated by Django 3.1.3 on 2022-04-07 14:33

from django.db import migrations, models
import django.db.models.manager
import djongo.models.fields
import vendorBackend.models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorBackend', '0004_vendormodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('session', djongo.models.fields.EmbeddedField(model_container=vendorBackend.models.session)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('Area', djongo.models.fields.ArrayField(model_container=vendorBackend.models.Area, model_form_class=vendorBackend.models.VendorForm)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
