# Generated by Django 3.1.3 on 2022-04-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorBackend', '0002_vendormodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorModel',
        ),
    ]
